// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type CommandStepManualRetryObjectAllowedValues interface {
	bool | string
}
type CommandStepManualRetryObjectAllowed struct {
	Bool   *bool
	String *string
}

func (e CommandStepManualRetryObjectAllowed) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

type CommandStepManualRetryObjectPermitOnPassedValues interface {
	bool | string
}
type CommandStepManualRetryObjectPermitOnPassed struct {
	Bool   *bool
	String *string
}

func (e CommandStepManualRetryObjectPermitOnPassed) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

type CommandStepManualRetryObject struct {
	Allowed        *CommandStepManualRetryObjectAllowed        `json:"allowed,omitempty"`
	PermitOnPassed *CommandStepManualRetryObjectPermitOnPassed `json:"permit_on_passed,omitempty"`
	Reason         *string                                     `json:"reason,omitempty"`
}
