// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type MatrixAdjustmentsWithValues interface {
	MatrixElementList | MatrixAdjustmentsWithObject
}
type MatrixAdjustmentsWith struct {
	MatrixElementList           *MatrixElementList
	MatrixAdjustmentsWithObject *MatrixAdjustmentsWithObject
}

func (e MatrixAdjustmentsWith) MarshalJSON() ([]byte, error) {
	if e.MatrixElementList != nil {
		return json.Marshal(e.MatrixElementList)
	}
	if e.MatrixAdjustmentsWithObject != nil {
		return json.Marshal(e.MatrixAdjustmentsWithObject)
	}
	return json.Marshal(nil)
}

type MatrixAdjustments struct {
	Skip     *Skip                  `json:"skip,omitempty"`
	SoftFail *SoftFail              `json:"soft_fail,omitempty"`
	With     *MatrixAdjustmentsWith `json:"with,omitempty"`
}
