// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type MatrixSetupObject = map[string]string
type MatrixSetupValues interface {
	MatrixElementList | MatrixSetupObject
}
type MatrixSetup struct {
	MatrixElementList *MatrixElementList
	MatrixSetup       *MatrixSetupObject
}

func (e MatrixSetup) MarshalJSON() ([]byte, error) {
	if e.MatrixElementList != nil {
		return json.Marshal(e.MatrixElementList)
	}
	if e.MatrixSetup != nil {
		return json.Marshal(e.MatrixSetup)
	}
	return json.Marshal(nil)
}
