// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type MatrixValues interface {
	MatrixElementList | MatrixObject
}
type Matrix struct {
	MatrixElementList *MatrixElementList
	MatrixObject      *MatrixObject
}

func (e Matrix) MarshalJSON() ([]byte, error) {
	if e.MatrixElementList != nil {
		return json.Marshal(e.MatrixElementList)
	}
	if e.MatrixObject != nil {
		return json.Marshal(e.MatrixObject)
	}
	return json.Marshal(nil)
}
