// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type NestedCommandStep struct {
	Command  *CommandStep `json:"command,omitempty"`
	Commands *CommandStep `json:"commands,omitempty"`
	Script   *CommandStep `json:"script,omitempty"`
}
