// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type NotifyPagerduty struct {
	If                   *string `json:"if,omitempty"`
	PagerdutyChangeEvent *string `json:"pagerduty_change_event,omitempty"`
}
