// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type PipelineStepsUnionValues interface {
	BlockStep | NestedBlockStep | StringBlockStep | InputStep | NestedInputStep | StringInputStep | CommandStep | NestedCommandStep | WaitStep | NestedWaitStep | StringWaitStep | TriggerStep | NestedTriggerStep | GroupStep
}
type PipelineStepsUnion struct {
	BlockStep         *BlockStep
	NestedBlockStep   *NestedBlockStep
	StringBlockStep   *StringBlockStep
	InputStep         *InputStep
	NestedInputStep   *NestedInputStep
	StringInputStep   *StringInputStep
	CommandStep       *CommandStep
	NestedCommandStep *NestedCommandStep
	WaitStep          *WaitStep
	NestedWaitStep    *NestedWaitStep
	StringWaitStep    *StringWaitStep
	TriggerStep       *TriggerStep
	NestedTriggerStep *NestedTriggerStep
	GroupStep         *GroupStep
}

func (e PipelineStepsUnion) MarshalJSON() ([]byte, error) {
	if e.BlockStep != nil {
		return json.Marshal(e.BlockStep)
	}
	if e.NestedBlockStep != nil {
		return json.Marshal(e.NestedBlockStep)
	}
	if e.StringBlockStep != nil {
		return json.Marshal(e.StringBlockStep)
	}
	if e.InputStep != nil {
		return json.Marshal(e.InputStep)
	}
	if e.NestedInputStep != nil {
		return json.Marshal(e.NestedInputStep)
	}
	if e.StringInputStep != nil {
		return json.Marshal(e.StringInputStep)
	}
	if e.CommandStep != nil {
		return json.Marshal(e.CommandStep)
	}
	if e.NestedCommandStep != nil {
		return json.Marshal(e.NestedCommandStep)
	}
	if e.WaitStep != nil {
		return json.Marshal(e.WaitStep)
	}
	if e.NestedWaitStep != nil {
		return json.Marshal(e.NestedWaitStep)
	}
	if e.StringWaitStep != nil {
		return json.Marshal(e.StringWaitStep)
	}
	if e.TriggerStep != nil {
		return json.Marshal(e.TriggerStep)
	}
	if e.NestedTriggerStep != nil {
		return json.Marshal(e.NestedTriggerStep)
	}
	if e.GroupStep != nil {
		return json.Marshal(e.GroupStep)
	}
	return json.Marshal(nil)
}

type PipelineSteps = []PipelineStepsUnion
