// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type PluginsValues interface {
	PluginsList | PluginsObject
}
type Plugins struct {
	PluginsList   *PluginsList
	PluginsObject *PluginsObject
}

func (e Plugins) MarshalJSON() ([]byte, error) {
	if e.PluginsList != nil {
		return json.Marshal(e.PluginsList)
	}
	if e.PluginsObject != nil {
		return json.Marshal(e.PluginsObject)
	}
	return json.Marshal(nil)
}
