// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type PluginsListObject = map[string]string
type PluginsListUnionValues interface {
	string | PluginsListObject
}
type PluginsListUnion struct {
	String      *string
	PluginsList *PluginsListObject
}

func (e PluginsListUnion) MarshalJSON() ([]byte, error) {
	if e.String != nil {
		return json.Marshal(e.String)
	}
	if e.PluginsList != nil {
		return json.Marshal(e.PluginsList)
	}
	return json.Marshal(nil)
}

type PluginsList = []PluginsListUnion
