// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type SelectFieldDefaultValues interface {
	string | []string
}
type SelectFieldDefault struct {
	String      *string
	StringArray []string
}

func (e SelectFieldDefault) MarshalJSON() ([]byte, error) {
	if e.String != nil {
		return json.Marshal(e.String)
	}
	if e.StringArray != nil {
		return json.Marshal(e.StringArray)
	}
	return json.Marshal(nil)
}

type SelectFieldMultipleValues interface {
	bool | string
}
type SelectFieldMultiple struct {
	Bool   *bool
	String *string
}

func (e SelectFieldMultiple) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

type SelectFieldRequiredValues interface {
	string | bool
}
type SelectFieldRequired struct {
	String *string
	Bool   *bool
}

func (e SelectFieldRequired) MarshalJSON() ([]byte, error) {
	if e.String != nil {
		return json.Marshal(e.String)
	}
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	return json.Marshal(nil)
}

type SelectField struct {
	Default  *SelectFieldDefault  `json:"default,omitempty"`
	Hint     *string              `json:"hint,omitempty"`
	Key      *string              `json:"key,omitempty"`
	Multiple *SelectFieldMultiple `json:"multiple,omitempty"`
	Options  []SelectFieldOption  `json:"options,omitempty"`
	Required *SelectFieldRequired `json:"required,omitempty"`
	Select   *string              `json:"select,omitempty"`
}
