// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type StringBlockStep string

var StringBlockStepValues = map[string]StringBlockStep{
	"block": "block",
}
