// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type TextFieldRequiredValues interface {
	bool | string
}
type TextFieldRequired struct {
	Bool   *bool
	String *string
}

func (e TextFieldRequired) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

type TextField struct {
	Default  *string            `json:"default,omitempty"`
	Format   *string            `json:"format,omitempty"`
	Hint     *string            `json:"hint,omitempty"`
	Key      *string            `json:"key,omitempty"`
	Required *TextFieldRequired `json:"required,omitempty"`
	Text     *string            `json:"text,omitempty"`
}
