require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - "lib/schema.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Exclude:
    - "lib/schema.rb"

Layout/LineLength:
  Exclude:
    - "lib/environment.rb"

Metrics/ModuleLength:
  Exclude:
    - "lib/environment.rb"

RSpec/ExampleLength:
  Max: 20
