#!/usr/bin/env bash

set -euo pipefail

echo "hello, world"
env|rev

# Build an image for the toolchain and load it into the local image store.
docker build --load --platform linux/amd64 -t buildkite-sdk-tools:latest .
