// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type AgentsValues interface {
	AgentsObject | AgentsList
}
type Agents struct {
	AgentsList   *AgentsList
	AgentsObject *AgentsObject
}

func (e Agents) MarshalJSON() ([]byte, error) {
	if e.AgentsObject != nil {
		return json.Marshal(e.AgentsObject)
	}
	if e.AgentsList != nil {
		return json.Marshal(e.AgentsList)
	}
	return json.Marshal(nil)
}
