// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

// Query rules to target specific agents in k=v format
type AgentsList = []string
