// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

// Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
type AllowDependencyFailureValues interface {
	bool | string
}

// Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
type AllowDependencyFailure struct {
	Bool   *bool
	String *string
}

func (e AllowDependencyFailure) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}
