// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type BlockStepBlockedState string

var BlockStepBlockedStateValues = map[string]BlockStepBlockedState{
	"passed":  "passed",
	"failed":  "failed",
	"running": "running",
}

type BlockStepType string

var BlockStepTypeValues = map[string]BlockStepType{
	"block": "block",
}

type BlockStep struct {
	AllowDependencyFailure *AllowDependencyFailure `json:"allow_dependency_failure,omitempty"`
	AllowedTeams           *AllowedTeams           `json:"allowed_teams,omitempty"`
	Block                  *string                 `json:"block,omitempty"`
	BlockedState           *BlockStepBlockedState  `json:"blocked_state,omitempty"`
	Branches               *Branches               `json:"branches,omitempty"`
	DependsOn              *DependsOn              `json:"depends_on,omitempty"`
	Fields                 *Fields                 `json:"fields,omitempty"`
	Id                     *string                 `json:"id,omitempty"`
	Identifier             *string                 `json:"identifier,omitempty"`
	If                     *string                 `json:"if,omitempty"`
	Key                    *string                 `json:"key,omitempty"`
	Label                  *string                 `json:"label,omitempty"`
	Name                   *string                 `json:"name,omitempty"`
	Prompt                 *string                 `json:"prompt,omitempty"`
	Type                   *BlockStepType          `json:"type,omitempty"`
}
