// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

// Which branches will include this step in their builds
type BranchesValues interface {
	string | []string
}

// Which branches will include this step in their builds
type Branches struct {
	String      *string
	StringArray []string
}

func (e Branches) MarshalJSON() ([]byte, error) {
	if e.String != nil {
		return json.Marshal(e.String)
	}
	if e.StringArray != nil {
		return json.Marshal(e.StringArray)
	}
	return json.Marshal(nil)
}
