// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

// Array of notification options for this step
type BuildNotifyItemValues interface {
	NotifySimple | NotifyEmail | NotifyBasecamp | NotifySlack | NotifyWebhook | NotifyPagerduty | NotifyGithubCommitStatus | NotifyGithubCheck
}

// Array of notification options for this step
type BuildNotifyItem struct {
	NotifyBasecamp           *NotifyBasecamp
	NotifyEmail              *NotifyEmail
	NotifyGithubCheck        *NotifyGithubCheck
	NotifyGithubCommitStatus *NotifyGithubCommitStatus
	NotifyPagerduty          *NotifyPagerduty
	NotifySimple             *NotifySimple
	NotifySlack              *NotifySlack
	NotifyWebhook            *NotifyWebhook
}

func (e BuildNotifyItem) MarshalJSON() ([]byte, error) {
	if e.NotifySimple != nil {
		return json.Marshal(e.NotifySimple)
	}
	if e.NotifyEmail != nil {
		return json.Marshal(e.NotifyEmail)
	}
	if e.NotifyBasecamp != nil {
		return json.Marshal(e.NotifyBasecamp)
	}
	if e.NotifySlack != nil {
		return json.Marshal(e.NotifySlack)
	}
	if e.NotifyWebhook != nil {
		return json.Marshal(e.NotifyWebhook)
	}
	if e.NotifyPagerduty != nil {
		return json.Marshal(e.NotifyPagerduty)
	}
	if e.NotifyGithubCommitStatus != nil {
		return json.Marshal(e.NotifyGithubCommitStatus)
	}
	if e.NotifyGithubCheck != nil {
		return json.Marshal(e.NotifyGithubCheck)
	}
	return json.Marshal(nil)
}

// Array of notification options for this step
type BuildNotify = []BuildNotifyItem
