// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type CacheObject struct {
	Name  *string  `json:"name,omitempty"`
	Paths []string `json:"paths,omitempty"`
	Size  *string  `json:"size,omitempty"`
}
type CacheValues interface {
	string | []string | CacheObject
}

// The paths for the caches to be used in the step
type Cache struct {
	Cache       *CacheObject
	String      *string
	StringArray []string
}

func (e Cache) MarshalJSON() ([]byte, error) {
	if e.Cache != nil {
		return json.Marshal(e.Cache)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	if e.StringArray != nil {
		return json.Marshal(e.StringArray)
	}
	return json.Marshal(nil)
}
