// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

// Whether to cancel the job as soon as the build is marked as failing
type CancelOnBuildFailingValues interface {
	bool | string
}

// Whether to cancel the job as soon as the build is marked as failing
type CancelOnBuildFailing struct {
	Bool   *bool
	String *string
}

func (e CancelOnBuildFailing) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}
