// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type CheckoutCommitVerification string

// Verify the checked-out commit is on the expected branch; strict fails the job on a definitive mismatch, warn only logs
var CheckoutCommitVerificationValues = map[string]CheckoutCommitVerification{
	"strict": "strict",
	"warn":   "warn",
}

// Number of commits to fetch when performing a shallow clone; omit for full history
type CheckoutDepthValues interface {
	int | string
}

// Number of commits to fetch when performing a shallow clone; omit for full history
type CheckoutDepth struct {
	Int    *int
	String *string
}

func (e CheckoutDepth) MarshalJSON() ([]byte, error) {
	if e.Int != nil {
		return json.Marshal(e.Int)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

// Custom flags passed to git commands during checkout. Flag strings are passed to git verbatim and are not sanitized; do not interpolate untrusted input. See the agent documentation for precedence and defaults: https://buildkite.com/docs/agent/v3/configuration
type CheckoutFlags struct {
	// Flags for the git checkout command
	Checkout *string `json:"checkout,omitempty"`
	// Flags for the git clean command
	Clean *string `json:"clean,omitempty"`
	// Flags for the git clone command
	Clone *string `json:"clone,omitempty"`
	// Flags for the git fetch command
	Fetch *string `json:"fetch,omitempty"`
}

// Whether to install Git LFS and fetch LFS objects after checkout. An explicit null is treated as unset
type CheckoutLfsValues interface {
	bool | string
}

// Whether to install Git LFS and fetch LFS objects after checkout. An explicit null is treated as unset
type CheckoutLfs struct {
	Bool   *bool
	String *string
}

func (e CheckoutLfs) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

// Skip the git checkout phase. An explicit null is treated as unset
type CheckoutSkipValues interface {
	bool | string
}

// Skip the git checkout phase. An explicit null is treated as unset
type CheckoutSkip struct {
	Bool   *bool
	String *string
}

func (e CheckoutSkip) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

// Repository-relative directory paths within the worktree, as one path or a list of paths; cone mode includes each directory recursively, not file globs
type CheckoutSparsePathsValues interface {
	string | []string
}

// Repository-relative directory paths within the worktree, as one path or a list of paths; cone mode includes each directory recursively, not file globs
type CheckoutSparsePaths struct {
	CheckoutSparsePath *string
	StringArray        []string
}

func (e CheckoutSparsePaths) MarshalJSON() ([]byte, error) {
	if e.CheckoutSparsePath != nil {
		return json.Marshal(e.CheckoutSparsePath)
	}
	if e.StringArray != nil {
		return json.Marshal(e.StringArray)
	}
	return json.Marshal(nil)
}

// Check out only the specified paths in git cone mode; requires git 2.27+ on the agent
type CheckoutSparse struct {
	// Repository-relative directory paths within the worktree, as one path or a list of paths; cone mode includes each directory recursively, not file globs
	Paths *CheckoutSparsePaths `json:"paths,omitempty"`
}

// Initialize, sync, update, and clean submodules recursively as part of checkout. An explicit null is treated as unset
type CheckoutSubmodulesValues interface {
	bool | string
}

// Initialize, sync, update, and clean submodules recursively as part of checkout. An explicit null is treated as unset
type CheckoutSubmodules struct {
	Bool   *bool
	String *string
}

func (e CheckoutSubmodules) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

// Configure git checkout behavior. Pipeline-level values are inherited by each step unless that step overrides the same key
type Checkout struct {
	// Verify the checked-out commit is on the expected branch; strict fails the job on a definitive mismatch, warn only logs
	CommitVerification *CheckoutCommitVerification `json:"commit_verification,omitempty"`
	// Number of commits to fetch when performing a shallow clone; omit for full history
	Depth *CheckoutDepth `json:"depth,omitempty"`
	// Custom flags passed to git commands during checkout. Flag strings are passed to git verbatim and are not sanitized; do not interpolate untrusted input. See the agent documentation for precedence and defaults: https://buildkite.com/docs/agent/v3/configuration
	Flags *CheckoutFlags `json:"flags,omitempty"`
	// Whether to install Git LFS and fetch LFS objects after checkout. An explicit null is treated as unset
	Lfs *CheckoutLfs `json:"lfs,omitempty"`
	// Skip the git checkout phase. An explicit null is treated as unset
	Skip *CheckoutSkip `json:"skip,omitempty"`
	// Check out only the specified paths in git cone mode; requires git 2.27+ on the agent
	Sparse *CheckoutSparse `json:"sparse,omitempty"`
	// Name of an SSH private key secret from Buildkite Secrets to use for git clone/fetch operations. The name must start with a letter, contain only letters, numbers, and underscores, and must not start with `buildkite` or `bk` (case-insensitive).
	SshSecret *string `json:"ssh_secret,omitempty"`
	// Initialize, sync, update, and clean submodules recursively as part of checkout. An explicit null is treated as unset
	Submodules *CheckoutSubmodules `json:"submodules,omitempty"`
}
