// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type CommandStepAutomaticRetryEnumValues interface {
	bool | string
}
type CommandStepAutomaticRetryEnum struct {
	Bool   *bool
	String *string
}

func (e CommandStepAutomaticRetryEnum) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

type CommandStepAutomaticRetryValues interface {
	CommandStepAutomaticRetryEnum | AutomaticRetry | AutomaticRetryList
}

// Whether to allow a job to retry automatically. If set to true, the retry conditions are set to the default value.
type CommandStepAutomaticRetry struct {
	AutomaticRetry                *AutomaticRetry
	AutomaticRetryList            *AutomaticRetryList
	CommandStepAutomaticRetryEnum *CommandStepAutomaticRetryEnum
}

func (e CommandStepAutomaticRetry) MarshalJSON() ([]byte, error) {
	if e.AutomaticRetry != nil {
		return json.Marshal(e.AutomaticRetry)
	}
	if e.AutomaticRetryList != nil {
		return json.Marshal(e.AutomaticRetryList)
	}
	if e.CommandStepAutomaticRetryEnum != nil {
		return json.Marshal(e.CommandStepAutomaticRetryEnum)
	}
	return json.Marshal(nil)
}
