// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type CommandStepCommandValues interface {
	[]string | string
}
type CommandStepCommand struct {
	String      *string
	StringArray []string
}

func (e CommandStepCommand) MarshalJSON() ([]byte, error) {
	if e.StringArray != nil {
		return json.Marshal(e.StringArray)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}
