// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type CommandStepManualRetryObjectAllowedValues interface {
	bool | string
}

// Whether or not this job can be retried manually
type CommandStepManualRetryObjectAllowed struct {
	Bool   *bool
	String *string
}

func (e CommandStepManualRetryObjectAllowed) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

type CommandStepManualRetryObjectPermitOnPassedValues interface {
	bool | string
}

// Whether or not this job can be retried after it has passed
type CommandStepManualRetryObjectPermitOnPassed struct {
	Bool   *bool
	String *string
}

func (e CommandStepManualRetryObjectPermitOnPassed) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

type CommandStepManualRetryObject struct {
	// Whether or not this job can be retried manually
	Allowed *CommandStepManualRetryObjectAllowed `json:"allowed,omitempty"`
	// Whether or not this job can be retried after it has passed
	PermitOnPassed *CommandStepManualRetryObjectPermitOnPassed `json:"permit_on_passed,omitempty"`
	// A string that will be displayed in a tooltip on the Retry button in Buildkite. This will only be displayed if the allowed attribute is set to false.
	Reason *string `json:"reason,omitempty"`
}
