// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type CommandStepManualRetryEnumValues interface {
	string | bool
}
type CommandStepManualRetryEnum struct {
	String *string
	Bool   *bool
}

func (e CommandStepManualRetryEnum) MarshalJSON() ([]byte, error) {
	if e.String != nil {
		return json.Marshal(e.String)
	}
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	return json.Marshal(nil)
}

type CommandStepManualRetryValues interface {
	CommandStepManualRetryEnum | CommandStepManualRetryObject
}
type CommandStepManualRetry struct {
	CommandStepManualRetryEnum   *CommandStepManualRetryEnum
	CommandStepManualRetryObject *CommandStepManualRetryObject
}

func (e CommandStepManualRetry) MarshalJSON() ([]byte, error) {
	if e.CommandStepManualRetryEnum != nil {
		return json.Marshal(e.CommandStepManualRetryEnum)
	}
	if e.CommandStepManualRetryObject != nil {
		return json.Marshal(e.CommandStepManualRetryObject)
	}
	return json.Marshal(nil)
}
