// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

// Array of notification options for this step
type CommandStepNotifyItemValues interface {
	NotifySimple | NotifyBasecamp | NotifySlack | NotifyGithubCommitStatus | NotifyGithubCheck
}

// Array of notification options for this step
type CommandStepNotifyItem struct {
	NotifyBasecamp           *NotifyBasecamp
	NotifyGithubCheck        *NotifyGithubCheck
	NotifyGithubCommitStatus *NotifyGithubCommitStatus
	NotifySimple             *NotifySimple
	NotifySlack              *NotifySlack
}

func (e CommandStepNotifyItem) MarshalJSON() ([]byte, error) {
	if e.NotifySimple != nil {
		return json.Marshal(e.NotifySimple)
	}
	if e.NotifyBasecamp != nil {
		return json.Marshal(e.NotifyBasecamp)
	}
	if e.NotifySlack != nil {
		return json.Marshal(e.NotifySlack)
	}
	if e.NotifyGithubCommitStatus != nil {
		return json.Marshal(e.NotifyGithubCommitStatus)
	}
	if e.NotifyGithubCheck != nil {
		return json.Marshal(e.NotifyGithubCheck)
	}
	return json.Marshal(nil)
}

// Array of notification options for this step
type CommandStepNotify = []CommandStepNotifyItem
