// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type DependsOnValues interface {
	string | DependsOnList
}
type DependsOn struct {
	String        *string
	DependsOnList *DependsOnList
}

func (e DependsOn) MarshalJSON() ([]byte, error) {
	if e.String != nil {
		return json.Marshal(e.String)
	}
	if e.DependsOnList != nil {
		return json.Marshal(e.DependsOnList)
	}
	return json.Marshal(nil)
}
