// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type DependsOnListObjectAllowFailureValues interface {
	bool | string
}
type DependsOnListObjectAllowFailure struct {
	Bool   *bool
	String *string
}

func (e DependsOnListObjectAllowFailure) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

type DependsOnListObject struct {
	AllowFailure *DependsOnListObjectAllowFailure `json:"allow_failure,omitempty"`
	Step         *string                          `json:"step,omitempty"`
}
type DependsOnListUnionValues interface {
	string | DependsOnListObject
}
type DependsOnListUnion struct {
	DependsOnList *DependsOnListObject
	String        *string
}

func (e DependsOnListUnion) MarshalJSON() ([]byte, error) {
	if e.String != nil {
		return json.Marshal(e.String)
	}
	if e.DependsOnList != nil {
		return json.Marshal(e.DependsOnList)
	}
	return json.Marshal(nil)
}

type DependsOnList = []DependsOnListUnion
