// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type FieldsUnionValues interface {
	TextField | SelectField
}
type FieldsUnion struct {
	SelectField *SelectField
	TextField   *TextField
}

func (e FieldsUnion) MarshalJSON() ([]byte, error) {
	if e.TextField != nil {
		return json.Marshal(e.TextField)
	}
	if e.SelectField != nil {
		return json.Marshal(e.SelectField)
	}
	return json.Marshal(nil)
}

type Fields = []FieldsUnion
