// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type FieldsItemValues interface {
	TextField | SelectField
}

// A list of input fields required to be filled out before unblocking the step
type FieldsItem struct {
	SelectField *SelectField
	TextField   *TextField
}

func (e FieldsItem) MarshalJSON() ([]byte, error) {
	if e.SelectField != nil {
		return json.Marshal(e.SelectField)
	}
	if e.TextField != nil {
		return json.Marshal(e.TextField)
	}
	return json.Marshal(nil)
}

// A list of input fields required to be filled out before unblocking the step
type Fields = []FieldsItem
