// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type GroupStep struct {
	// Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
	AllowDependencyFailure *AllowDependencyFailure `json:"allow_dependency_failure,omitempty"`
	// The step keys for a step to depend on
	DependsOn *DependsOn `json:"depends_on,omitempty"`
	// The name to give to this group of steps
	Group *string `json:"group,omitempty"`
	// A unique identifier for a step, must not resemble a UUID
	Id *string `json:"id,omitempty"`
	// A unique identifier for a step, must not resemble a UUID
	Identifier *string `json:"identifier,omitempty"`
	// A boolean expression that omits the step when false
	If *string `json:"if,omitempty"`
	// Agent-applied attribute: A glob pattern that omits the step from a build if it does not match any files changed in the build. Can be a single pattern, list of patterns, or an object with include/exclude attributes.
	IfChanged *IfChanged `json:"if_changed,omitempty"`
	// A unique identifier for a step, must not resemble a UUID
	Key *string `json:"key,omitempty"`
	// The name to give to this group of steps
	Label *string `json:"label,omitempty"`
	// The name to give to this group of steps
	Name *string `json:"name,omitempty"`
	// Array of notification options for this step
	Notify *BuildNotify `json:"notify,omitempty"`
	// Whether this step should be skipped. Passing a string provides a reason for skipping this command
	Skip *Skip `json:"skip,omitempty"`
	// A list of steps
	Steps *GroupSteps `json:"steps,omitempty"`
}
