// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type GroupStep struct {
	AllowDependencyFailure *AllowDependencyFailure `json:"allow_dependency_failure,omitempty"`
	DependsOn              *DependsOn              `json:"depends_on,omitempty"`
	Group                  *string                 `json:"group,omitempty"`
	Id                     *string                 `json:"id,omitempty"`
	Identifier             *string                 `json:"identifier,omitempty"`
	If                     *string                 `json:"if,omitempty"`
	IfChanged              *string                 `json:"if_changed,omitempty"`
	Key                    *string                 `json:"key,omitempty"`
	Label                  *string                 `json:"label,omitempty"`
	Name                   *string                 `json:"name,omitempty"`
	Notify                 *BuildNotify            `json:"notify,omitempty"`
	Skip                   *Skip                   `json:"skip,omitempty"`
	Steps                  *GroupSteps             `json:"steps,omitempty"`
}
