// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

// A list of steps
type GroupStepsUnionValues interface {
	BlockStep | NestedBlockStep | StringBlockStep | InputStep | NestedInputStep | StringInputStep | CommandStep | NestedCommandStep | WaitStep | NestedWaitStep | StringWaitStep | TriggerStep | NestedTriggerStep
}

// A list of steps
type GroupStepsUnion struct {
	BlockStep         *BlockStep
	CommandStep       *CommandStep
	InputStep         *InputStep
	NestedBlockStep   *NestedBlockStep
	NestedCommandStep *NestedCommandStep
	NestedInputStep   *NestedInputStep
	NestedTriggerStep *NestedTriggerStep
	NestedWaitStep    *NestedWaitStep
	// Pauses the execution of a build and waits on a user to unblock it
	StringBlockStep *StringBlockStep
	// Pauses the execution of a build and waits on a user to unblock it
	StringInputStep *StringInputStep
	// Waits for previous steps to pass before continuing
	StringWaitStep *StringWaitStep
	TriggerStep    *TriggerStep
	WaitStep       *WaitStep
}

func (e GroupStepsUnion) MarshalJSON() ([]byte, error) {
	if e.BlockStep != nil {
		return json.Marshal(e.BlockStep)
	}
	if e.NestedBlockStep != nil {
		return json.Marshal(e.NestedBlockStep)
	}
	if e.StringBlockStep != nil {
		return json.Marshal(e.StringBlockStep)
	}
	if e.InputStep != nil {
		return json.Marshal(e.InputStep)
	}
	if e.NestedInputStep != nil {
		return json.Marshal(e.NestedInputStep)
	}
	if e.StringInputStep != nil {
		return json.Marshal(e.StringInputStep)
	}
	if e.CommandStep != nil {
		return json.Marshal(e.CommandStep)
	}
	if e.NestedCommandStep != nil {
		return json.Marshal(e.NestedCommandStep)
	}
	if e.WaitStep != nil {
		return json.Marshal(e.WaitStep)
	}
	if e.NestedWaitStep != nil {
		return json.Marshal(e.NestedWaitStep)
	}
	if e.StringWaitStep != nil {
		return json.Marshal(e.StringWaitStep)
	}
	if e.TriggerStep != nil {
		return json.Marshal(e.TriggerStep)
	}
	if e.NestedTriggerStep != nil {
		return json.Marshal(e.NestedTriggerStep)
	}
	return json.Marshal(nil)
}

// A list of steps
type GroupSteps = []GroupStepsUnion
