// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

// Agent-applied attribute: A glob pattern that omits the step from a build if it does not match any files changed in the build.
type IfChanged = string
