// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type InputStepType string

var InputStepTypeValues = map[string]InputStepType{
	"input": "input",
}

type InputStep struct {
	AllowDependencyFailure *AllowDependencyFailure `json:"allow_dependency_failure,omitempty"`
	AllowedTeams           *AllowedTeams           `json:"allowed_teams,omitempty"`
	Branches               *Branches               `json:"branches,omitempty"`
	DependsOn              *DependsOn              `json:"depends_on,omitempty"`
	Fields                 *Fields                 `json:"fields,omitempty"`
	Id                     *string                 `json:"id,omitempty"`
	Identifier             *string                 `json:"identifier,omitempty"`
	If                     *string                 `json:"if,omitempty"`
	Input                  *string                 `json:"input,omitempty"`
	Key                    *string                 `json:"key,omitempty"`
	Label                  *string                 `json:"label,omitempty"`
	Name                   *string                 `json:"name,omitempty"`
	Prompt                 *string                 `json:"prompt,omitempty"`
	Type                   *InputStepType          `json:"type,omitempty"`
}
