// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

// A unique identifier for a step, must not resemble a UUID
type Key = string
