// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

// The label that will be displayed in the pipeline visualisation in Buildkite. Supports emoji.
type Label = string
