// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type MatrixAdjustmentsWithValues interface {
	MatrixElementList | MatrixAdjustmentsWithObject
}
type MatrixAdjustmentsWith struct {
	// Build Matrix dimension element
	MatrixAdjustmentsWithObject *MatrixAdjustmentsWithObject
	MatrixElementList           *MatrixElementList
}

func (e MatrixAdjustmentsWith) MarshalJSON() ([]byte, error) {
	if e.MatrixAdjustmentsWithObject != nil {
		return json.Marshal(e.MatrixAdjustmentsWithObject)
	}
	if e.MatrixElementList != nil {
		return json.Marshal(e.MatrixElementList)
	}
	return json.Marshal(nil)
}

// An adjustment to a Build Matrix
type MatrixAdjustments struct {
	// Whether this step should be skipped. Passing a string provides a reason for skipping this command
	Skip *Skip `json:"skip,omitempty"`
	// The conditions for marking the step as a soft-fail.
	SoftFail *SoftFail              `json:"soft_fail,omitempty"`
	With     *MatrixAdjustmentsWith `json:"with,omitempty"`
}
