// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type MatrixElementValues interface {
	string | int | bool
}
type MatrixElement struct {
	Bool   *bool
	Int    *int
	String *string
}

func (e MatrixElement) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.Int != nil {
		return json.Marshal(e.Int)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}
