// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

// Configuration for multi-dimension Build Matrix
type MatrixObject struct {
	// An adjustment to a Build Matrix
	Adjustments []MatrixAdjustments `json:"adjustments,omitempty"`
	Setup       *MatrixSetup        `json:"setup,omitempty"`
}
