// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type MatrixObject struct {
	Adjustments []MatrixAdjustments `json:"adjustments,omitempty"`
	Setup       *MatrixSetup        `json:"setup,omitempty"`
}
