// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type NestedWaitStep struct {
	Wait   *WaitStep `json:"wait,omitempty"`
	Waiter *WaitStep `json:"waiter,omitempty"`
}
