// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type NotifyGithubCommitStatusGithubCommitStatus struct {
	// GitHub commit status name
	Context *string `json:"context,omitempty"`
}
type NotifyGithubCommitStatus struct {
	GithubCommitStatus *NotifyGithubCommitStatusGithubCommitStatus `json:"github_commit_status,omitempty"`
	// A boolean expression that omits the step when false
	If *string `json:"if,omitempty"`
}
