// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type NotifySimple string

var NotifySimpleValues = map[string]NotifySimple{
	"github_check":         "github_check",
	"github_commit_status": "github_commit_status",
}
