// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type NotifyEmail struct {
	Email *string `json:"email,omitempty"`
	If    *string `json:"if,omitempty"`
}
