// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type NotifySlackObject struct {
	Channels []string `json:"channels,omitempty"`
	Message  *string  `json:"message,omitempty"`
}
