// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type NotifySlackSlackValues interface {
	string | NotifySlackObject
}
type NotifySlackSlack struct {
	NotifySlackObject *NotifySlackObject
	String            *string
}

func (e NotifySlackSlack) MarshalJSON() ([]byte, error) {
	if e.String != nil {
		return json.Marshal(e.String)
	}
	if e.NotifySlackObject != nil {
		return json.Marshal(e.NotifySlackObject)
	}
	return json.Marshal(nil)
}

type NotifySlack struct {
	// A boolean expression that omits the step when false
	If    *string           `json:"if,omitempty"`
	Slack *NotifySlackSlack `json:"slack,omitempty"`
}
