// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type NotifyGithubCommitStatusGithubCommitStatus struct {
	Context *string `json:"context,omitempty"`
}
type NotifyGithubCommitStatus struct {
	GithubCommitStatus *NotifyGithubCommitStatusGithubCommitStatus `json:"github_commit_status,omitempty"`
	If                 *string                                     `json:"if,omitempty"`
}
