// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type NotifyBasecamp struct {
	BasecampCampfire *string `json:"basecamp_campfire,omitempty"`
	If               *string `json:"if,omitempty"`
}
