// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type Pipeline struct {
	Notify *BuildNotify   `json:"notify,omitempty"`
	Image  *Image         `json:"image,omitempty"`
	Steps  *PipelineSteps `json:"steps,omitempty"`
	Env    *Env           `json:"env,omitempty"`
	Agents *Agents        `json:"agents,omitempty"`
}

func (p Pipeline) ToJSON() (string, error) {
	rawJSON, err := json.Marshal(p)
	if err != nil {
		return "", err
	}
	return string(rawJSON), nil
}
