// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type PipelineCheckoutCommitVerification string

// Verify the checked-out commit is on the expected branch; strict fails the job on a definitive mismatch, warn only logs
var PipelineCheckoutCommitVerificationValues = map[string]PipelineCheckoutCommitVerification{
	"strict": "strict",
	"warn":   "warn",
}

// Number of commits to fetch when performing a shallow clone; omit for full history
type PipelineCheckoutDepthValues interface {
	int | string
}

// Number of commits to fetch when performing a shallow clone; omit for full history
type PipelineCheckoutDepth struct {
	Int    *int
	String *string
}

func (e PipelineCheckoutDepth) MarshalJSON() ([]byte, error) {
	if e.Int != nil {
		return json.Marshal(e.Int)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

// Custom flags passed to git commands during checkout. Flag strings are passed to git verbatim and are not sanitized; do not interpolate untrusted input. See the agent documentation for precedence and defaults: https://buildkite.com/docs/agent/v3/configuration
type PipelineCheckoutFlags struct {
	// Flags for the git checkout command
	Checkout *string `json:"checkout,omitempty"`
	// Flags for the git clean command
	Clean *string `json:"clean,omitempty"`
	// Flags for the git clone command
	Clone *string `json:"clone,omitempty"`
	// Flags for the git fetch command
	Fetch *string `json:"fetch,omitempty"`
}

// Whether to install Git LFS and fetch LFS objects after checkout. An explicit null is treated as unset
type PipelineCheckoutLfsValues interface {
	bool | string
}

// Whether to install Git LFS and fetch LFS objects after checkout. An explicit null is treated as unset
type PipelineCheckoutLfs struct {
	Bool   *bool
	String *string
}

func (e PipelineCheckoutLfs) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

// Skip the git checkout phase. An explicit null is treated as unset
type PipelineCheckoutSkipValues interface {
	bool | string
}

// Skip the git checkout phase. An explicit null is treated as unset
type PipelineCheckoutSkip struct {
	Bool   *bool
	String *string
}

func (e PipelineCheckoutSkip) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

// Repository-relative directory paths within the worktree, as one path or a list of paths; cone mode includes each directory recursively, not file globs
type PipelineCheckoutSparsePathsValues interface {
	string | []string
}

// Repository-relative directory paths within the worktree, as one path or a list of paths; cone mode includes each directory recursively, not file globs
type PipelineCheckoutSparsePaths struct {
	CheckoutSparsePath *string
	StringArray        []string
}

func (e PipelineCheckoutSparsePaths) MarshalJSON() ([]byte, error) {
	if e.CheckoutSparsePath != nil {
		return json.Marshal(e.CheckoutSparsePath)
	}
	if e.StringArray != nil {
		return json.Marshal(e.StringArray)
	}
	return json.Marshal(nil)
}

// Check out only the specified paths in git cone mode; requires git 2.27+ on the agent
type PipelineCheckoutSparse struct {
	// Repository-relative directory paths within the worktree, as one path or a list of paths; cone mode includes each directory recursively, not file globs
	Paths *PipelineCheckoutSparsePaths `json:"paths,omitempty"`
}

// Initialize, sync, update, and clean submodules recursively as part of checkout. An explicit null is treated as unset
type PipelineCheckoutSubmodulesValues interface {
	bool | string
}

// Initialize, sync, update, and clean submodules recursively as part of checkout. An explicit null is treated as unset
type PipelineCheckoutSubmodules struct {
	Bool   *bool
	String *string
}

func (e PipelineCheckoutSubmodules) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

// Configure git checkout behavior. Pipeline-level values are inherited by each step unless that step overrides the same key. ssh_secret is step-level only and is not valid here
type PipelineCheckout struct {
	// Verify the checked-out commit is on the expected branch; strict fails the job on a definitive mismatch, warn only logs
	CommitVerification *PipelineCheckoutCommitVerification `json:"commit_verification,omitempty"`
	// Number of commits to fetch when performing a shallow clone; omit for full history
	Depth *PipelineCheckoutDepth `json:"depth,omitempty"`
	// Custom flags passed to git commands during checkout. Flag strings are passed to git verbatim and are not sanitized; do not interpolate untrusted input. See the agent documentation for precedence and defaults: https://buildkite.com/docs/agent/v3/configuration
	Flags *PipelineCheckoutFlags `json:"flags,omitempty"`
	// Whether to install Git LFS and fetch LFS objects after checkout. An explicit null is treated as unset
	Lfs *PipelineCheckoutLfs `json:"lfs,omitempty"`
	// Skip the git checkout phase. An explicit null is treated as unset
	Skip *PipelineCheckoutSkip `json:"skip,omitempty"`
	// Check out only the specified paths in git cone mode; requires git 2.27+ on the agent
	Sparse *PipelineCheckoutSparse `json:"sparse,omitempty"`
	// Initialize, sync, update, and clean submodules recursively as part of checkout. An explicit null is treated as unset
	Submodules *PipelineCheckoutSubmodules `json:"submodules,omitempty"`
}
