// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

// A map of plugins for this step. Deprecated: please use the array syntax.
type PluginsObject = map[string]interface{}
