// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type PluginsValues interface {
	PluginsList | PluginsObject
}
type Plugins struct {
	// Array of plugins for this step
	PluginsList *PluginsList
	// A map of plugins for this step. Deprecated: please use the array syntax.
	PluginsObject *PluginsObject
}

func (e Plugins) MarshalJSON() ([]byte, error) {
	if e.PluginsList != nil {
		return json.Marshal(e.PluginsList)
	}
	if e.PluginsObject != nil {
		return json.Marshal(e.PluginsObject)
	}
	return json.Marshal(nil)
}
