// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type PluginsListObject = map[string]interface{}
type PluginsListItemValues interface {
	string | PluginsListObject
}

// Array of plugins for this step
type PluginsListItem struct {
	PluginsList *PluginsListObject
	String      *string
}

func (e PluginsListItem) MarshalJSON() ([]byte, error) {
	if e.PluginsList != nil {
		return json.Marshal(e.PluginsList)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

// Array of plugins for this step
type PluginsList = []PluginsListItem
