// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

// The instructional message displayed in the dialog box when the unblock step is activated
type Prompt = string
