// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type SecretsObject = map[string]string

// A list of secret names or a mapping of environment variable names to secret names to be made available to the build or step
type SecretsValues interface {
	[]string | SecretsObject
}

// A list of secret names or a mapping of environment variable names to secret names to be made available to the build or step
type Secrets struct {
	Secrets     *SecretsObject
	StringArray []string
}

func (e Secrets) MarshalJSON() ([]byte, error) {
	if e.StringArray != nil {
		return json.Marshal(e.StringArray)
	}
	if e.Secrets != nil {
		return json.Marshal(e.Secrets)
	}
	return json.Marshal(nil)
}
