// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

// Whether the field is required for form submission
type SelectFieldOptionRequiredValues interface {
	bool | string
}

// Whether the field is required for form submission
type SelectFieldOptionRequired struct {
	Bool   *bool
	String *string
}

func (e SelectFieldOptionRequired) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

type SelectFieldOption struct {
	// The text displayed directly under the select field’s label
	Hint *string `json:"hint,omitempty"`
	// The text displayed on the select list item
	Label *string `json:"label,omitempty"`
	// Whether the field is required for form submission
	Required *SelectFieldOptionRequired `json:"required,omitempty"`
	// The value to be stored as meta-data
	Value *string `json:"value,omitempty"`
}
