// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type SelectFieldOptionRequiredValues interface {
	string | bool
}
type SelectFieldOptionRequired struct {
	String *string
	Bool   *bool
}

func (e SelectFieldOptionRequired) MarshalJSON() ([]byte, error) {
	if e.String != nil {
		return json.Marshal(e.String)
	}
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	return json.Marshal(nil)
}

type SelectFieldOption struct {
	Hint     *string                    `json:"hint,omitempty"`
	Label    *string                    `json:"label,omitempty"`
	Required *SelectFieldOptionRequired `json:"required,omitempty"`
	Value    *string                    `json:"value,omitempty"`
}
