// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type SelectFieldDefaultValues interface {
	string | []string
}

// The value of the option(s) that will be pre-selected in the dropdown
type SelectFieldDefault struct {
	String      *string
	StringArray []string
}

func (e SelectFieldDefault) MarshalJSON() ([]byte, error) {
	if e.String != nil {
		return json.Marshal(e.String)
	}
	if e.StringArray != nil {
		return json.Marshal(e.StringArray)
	}
	return json.Marshal(nil)
}

type SelectFieldMultipleValues interface {
	bool | string
}

// Whether more than one option may be selected
type SelectFieldMultiple struct {
	Bool   *bool
	String *string
}

func (e SelectFieldMultiple) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

type SelectFieldRequiredValues interface {
	bool | string
}

// Whether the field is required for form submission
type SelectFieldRequired struct {
	Bool   *bool
	String *string
}

func (e SelectFieldRequired) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}

type SelectField struct {
	// The value of the option(s) that will be pre-selected in the dropdown
	Default *SelectFieldDefault `json:"default,omitempty"`
	// The explanatory text that is shown after the label
	Hint *string `json:"hint,omitempty"`
	// The meta-data key that stores the field's input
	Key *string `json:"key,omitempty"`
	// Whether more than one option may be selected
	Multiple *SelectFieldMultiple `json:"multiple,omitempty"`
	Options  []SelectFieldOption  `json:"options,omitempty"`
	// Whether the field is required for form submission
	Required *SelectFieldRequired `json:"required,omitempty"`
	// The text input name
	Select *string `json:"select,omitempty"`
}
