// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

// Whether this step should be skipped. Passing a string provides a reason for skipping this command
type SkipValues interface {
	bool | string
}

// Whether this step should be skipped. Passing a string provides a reason for skipping this command
type Skip struct {
	Bool   *bool
	String *string
}

func (e Skip) MarshalJSON() ([]byte, error) {
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	if e.String != nil {
		return json.Marshal(e.String)
	}
	return json.Marshal(nil)
}
