// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type SoftFailObjectExitStatusEnum string

var SoftFailObjectExitStatusEnumValues = map[string]SoftFailObjectExitStatusEnum{
	"*": "*",
}

// The exit status number that will cause this job to soft-fail
type SoftFailObjectExitStatusValues interface {
	SoftFailObjectExitStatusEnum | int
}

// The exit status number that will cause this job to soft-fail
type SoftFailObjectExitStatus struct {
	Int                          *int
	SoftFailObjectExitStatusEnum *SoftFailObjectExitStatusEnum
}

func (e SoftFailObjectExitStatus) MarshalJSON() ([]byte, error) {
	if e.SoftFailObjectExitStatusEnum != nil {
		return json.Marshal(e.SoftFailObjectExitStatusEnum)
	}
	if e.Int != nil {
		return json.Marshal(e.Int)
	}
	return json.Marshal(nil)
}

type SoftFailObject struct {
	// The exit status number that will cause this job to soft-fail
	ExitStatus *SoftFailObjectExitStatus `json:"exit_status,omitempty"`
}
