// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

import "encoding/json"

type SoftFailEnumValues interface {
	string | bool
}
type SoftFailEnum struct {
	String *string
	Bool   *bool
}

func (e SoftFailEnum) MarshalJSON() ([]byte, error) {
	if e.String != nil {
		return json.Marshal(e.String)
	}
	if e.Bool != nil {
		return json.Marshal(e.Bool)
	}
	return json.Marshal(nil)
}

type SoftFailValues interface {
	SoftFailEnum | SoftFailList
}
type SoftFail struct {
	SoftFailEnum *SoftFailEnum
	SoftFailList *SoftFailList
}

func (e SoftFail) MarshalJSON() ([]byte, error) {
	if e.SoftFailEnum != nil {
		return json.Marshal(e.SoftFailEnum)
	}
	if e.SoftFailList != nil {
		return json.Marshal(e.SoftFailList)
	}
	return json.Marshal(nil)
}
