// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type StringInputStep string

// Pauses the execution of a build and waits on a user to unblock it
var StringInputStepValues = map[string]StringInputStep{
	"input": "input",
}
