// Code generated by the gen package. DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package buildkite

type StringWaitStep string

// Waits for previous steps to pass before continuing
var StringWaitStepValues = map[string]StringWaitStep{
	"wait":   "wait",
	"waiter": "waiter",
}
