# Code generated by the gen package. DO NOT EDIT.
# *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***
from __future__ import annotations
import sys
from pathlib import Path

if sys.version_info >= (3, 12):
    from typing import Literal, List, Dict, Any, Optional, TypedDict, NotRequired
else:
    from typing import Literal, List, Dict, Any, Optional

    from typing_extensions import TypedDict, NotRequired

from pydantic import AliasChoices, BaseModel, Field

# Query rules to target specific agents
AgentsObject = Dict[str, Any]

# Query rules to target specific agents in k=v format
AgentsList = List[str]

Agents = AgentsObject | AgentsList

# Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
AllowDependencyFailure = Literal[True, False, "true", "false"]

# A list of teams that are permitted to unblock this step, whose values are a list of one or more team slugs or IDs
AllowedTeams = str | List[str]

AutomaticRetryArgs = TypedDict(
    "AutomaticRetryArgs",
    {
        # The exit status number that will cause this job to retry
        "exit_status": NotRequired[Literal["*"] | int | List[int]],
        # The number of times this job can be retried
        "limit": NotRequired["int"],
        # The exit signal, if any, that may be retried
        "signal": NotRequired["str"],
        # The exit signal reason, if any, that may be retried
        "signal_reason": NotRequired[
            Literal[
                "*",
                "none",
                "agent_incompatible",
                "agent_refused",
                "agent_stop",
                "cancel",
                "process_run_error",
                "signature_rejected",
                "stack_error",
            ]
        ],
    },
)


class AutomaticRetry(BaseModel):
    # The exit status number that will cause this job to retry
    exit_status: Optional[Literal["*"] | int | List[int]] = None
    # The number of times this job can be retried
    limit: Optional[int] = None
    # The exit signal, if any, that may be retried
    signal: Optional[str] = None
    # The exit signal reason, if any, that may be retried
    signal_reason: Optional[
        Literal[
            "*",
            "none",
            "agent_incompatible",
            "agent_refused",
            "agent_stop",
            "cancel",
            "process_run_error",
            "signature_rejected",
            "stack_error",
        ]
    ] = None

    @classmethod
    def from_dict(cls, data: AutomaticRetryArgs) -> AutomaticRetry:
        return cls.model_validate({**data})


AutomaticRetryList = List[AutomaticRetry | AutomaticRetryArgs]

DependsOnListObjectArgs = TypedDict(
    "DependsOnListObjectArgs",
    {
        "allow_failure": NotRequired[Literal[True, False, "true", "false"]],
        "step": NotRequired["str"],
    },
)


class DependsOnListObject(BaseModel):
    allow_failure: Optional[Literal[True, False, "true", "false"]] = None
    step: Optional[str] = None

    @classmethod
    def from_dict(cls, data: DependsOnListObjectArgs) -> DependsOnListObject:
        return cls.model_validate({**data})


DependsOnList = List[str | DependsOnListObject | DependsOnListObjectArgs]

TextFieldArgs = TypedDict(
    "TextFieldArgs",
    {
        # The value that is pre-filled in the text field
        "default": NotRequired["str"],
        # The format must be a regular expression implicitly anchored to the beginning and end of the input and is functionally equivalent to the HTML5 pattern attribute.
        "format": NotRequired["str"],
        # The explanatory text that is shown after the label
        "hint": NotRequired["str"],
        # The meta-data key that stores the field's input
        "key": "str",
        # Whether the field is required for form submission
        "required": NotRequired[Literal[True, False, "true", "false"]],
        # The text input name
        "text": NotRequired["str"],
    },
)


class TextField(BaseModel):
    # The value that is pre-filled in the text field
    default: Optional[str] = None
    # The format must be a regular expression implicitly anchored to the beginning and end of the input and is functionally equivalent to the HTML5 pattern attribute.
    format: Optional[str] = None
    # The explanatory text that is shown after the label
    hint: Optional[str] = None
    # The meta-data key that stores the field's input
    key: str
    # Whether the field is required for form submission
    required: Optional[Literal[True, False, "true", "false"]] = None
    # The text input name
    text: Optional[str] = None

    @classmethod
    def from_dict(cls, data: TextFieldArgs) -> TextField:
        return cls.model_validate({**data})


SelectFieldOptionArgs = TypedDict(
    "SelectFieldOptionArgs",
    {
        # The text displayed directly under the select field’s label
        "hint": NotRequired["str"],
        # The text displayed on the select list item
        "label": "str",
        # Whether the field is required for form submission
        "required": NotRequired[Literal[True, False, "true", "false"]],
        # The value to be stored as meta-data
        "value": "str",
    },
)


class SelectFieldOption(BaseModel):
    # The text displayed directly under the select field’s label
    hint: Optional[str] = None
    # The text displayed on the select list item
    label: str
    # Whether the field is required for form submission
    required: Optional[Literal[True, False, "true", "false"]] = None
    # The value to be stored as meta-data
    value: str

    @classmethod
    def from_dict(cls, data: SelectFieldOptionArgs) -> SelectFieldOption:
        return cls.model_validate({**data})


SelectFieldArgs = TypedDict(
    "SelectFieldArgs",
    {
        # The value of the option(s) that will be pre-selected in the dropdown
        "default": NotRequired["str | List[str]"],
        # The explanatory text that is shown after the label
        "hint": NotRequired["str"],
        # The meta-data key that stores the field's input
        "key": "str",
        # Whether more than one option may be selected
        "multiple": NotRequired[Literal[True, False, "true", "false"]],
        "options": "List[SelectFieldOptionArgs]",
        # Whether the field is required for form submission
        "required": NotRequired[Literal[True, False, "true", "false"]],
        # The text input name
        "select": NotRequired["str"],
    },
)


class SelectField(BaseModel):
    # The value of the option(s) that will be pre-selected in the dropdown
    default: Optional[str | List[str]] = None
    # The explanatory text that is shown after the label
    hint: Optional[str] = None
    # The meta-data key that stores the field's input
    key: str
    # Whether more than one option may be selected
    multiple: Optional[Literal[True, False, "true", "false"]] = None
    options: List[SelectFieldOption]
    # Whether the field is required for form submission
    required: Optional[Literal[True, False, "true", "false"]] = None
    # The text input name
    select: Optional[str] = None

    @classmethod
    def from_dict(cls, data: SelectFieldArgs) -> SelectField:
        return cls.model_validate({**data})


BlockStepArgs = TypedDict(
    "BlockStepArgs",
    {
        # Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
        "allow_dependency_failure": NotRequired["AllowDependencyFailure"],
        # A list of teams that are permitted to unblock this step, whose values are a list of one or more team slugs or IDs
        "allowed_teams": NotRequired["AllowedTeams"],
        # The label of the block step
        "block": NotRequired["str"],
        # The state that the build is set to when the build is blocked by this block step
        "blocked_state": NotRequired[Literal["passed", "failed", "running"]],
        # Which branches will include this step in their builds
        "branches": NotRequired["Branches"],
        # The step keys for a step to depend on
        "depends_on": NotRequired["DependsOn"],
        # A list of input fields required to be filled out before unblocking the step
        "fields": NotRequired["Fields"],
        # A unique identifier for a step, must not resemble a UUID
        "id": NotRequired["str"],
        # A unique identifier for a step, must not resemble a UUID
        "identifier": NotRequired["str"],
        # A boolean expression that omits the step when false
        "if": NotRequired["If"],
        # A unique identifier for a step, must not resemble a UUID
        "key": NotRequired["str"],
        # The label of the block step
        "label": NotRequired["str"],
        # The label of the block step
        "name": NotRequired["str"],
        # The instructional message displayed in the dialog box when the unblock step is activated
        "prompt": NotRequired["str"],
        "type": NotRequired[Literal["block"]],
    },
)


class BlockStep(BaseModel):
    # Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
    allow_dependency_failure: Optional[AllowDependencyFailure] = None
    # A list of teams that are permitted to unblock this step, whose values are a list of one or more team slugs or IDs
    allowed_teams: Optional[AllowedTeams] = None
    # The label of the block step
    block: Optional[str] = None
    # The state that the build is set to when the build is blocked by this block step
    blocked_state: Optional[Literal["passed", "failed", "running"]] = None
    # Which branches will include this step in their builds
    branches: Optional[Branches] = None
    # The step keys for a step to depend on
    depends_on: Optional[DependsOn] = None
    # A list of input fields required to be filled out before unblocking the step
    fields: Optional[Fields] = None
    # A unique identifier for a step, must not resemble a UUID
    id: Optional[str] = None
    # A unique identifier for a step, must not resemble a UUID
    identifier: Optional[str] = None
    # A boolean expression that omits the step when false
    step_if: Optional[If] = Field(
        validation_alias=AliasChoices("if", "step_if"),
        serialization_alias="if",
        default=None,
    )
    # A unique identifier for a step, must not resemble a UUID
    key: Optional[str] = None
    # The label of the block step
    label: Optional[str] = None
    # The label of the block step
    name: Optional[str] = None
    # The instructional message displayed in the dialog box when the unblock step is activated
    prompt: Optional[str] = None
    type: Optional[Literal["block"]] = None

    @classmethod
    def from_dict(cls, data: BlockStepArgs) -> BlockStep:
        step_if = {"step_if": data["if"]} if "if" in data else {}
        return cls.model_validate({**data, **step_if})


# Which branches will include this step in their builds
Branches = str | List[str]

NotifySimple = Literal["github_check", "github_commit_status"]

NotifyEmailArgs = TypedDict(
    "NotifyEmailArgs",
    {
        "email": NotRequired["str"],
        # A boolean expression that omits the step when false
        "if": NotRequired["If"],
    },
)


class NotifyEmail(BaseModel):
    email: Optional[str] = None
    # A boolean expression that omits the step when false
    step_if: Optional[If] = Field(
        validation_alias=AliasChoices("if", "step_if"),
        serialization_alias="if",
        default=None,
    )

    @classmethod
    def from_dict(cls, data: NotifyEmailArgs) -> NotifyEmail:
        step_if = {"step_if": data["if"]} if "if" in data else {}
        return cls.model_validate({**data, **step_if})


NotifyBasecampArgs = TypedDict(
    "NotifyBasecampArgs",
    {
        "basecamp_campfire": NotRequired["str"],
        # A boolean expression that omits the step when false
        "if": NotRequired["If"],
    },
)


class NotifyBasecamp(BaseModel):
    basecamp_campfire: Optional[str] = None
    # A boolean expression that omits the step when false
    step_if: Optional[If] = Field(
        validation_alias=AliasChoices("if", "step_if"),
        serialization_alias="if",
        default=None,
    )

    @classmethod
    def from_dict(cls, data: NotifyBasecampArgs) -> NotifyBasecamp:
        step_if = {"step_if": data["if"]} if "if" in data else {}
        return cls.model_validate({**data, **step_if})


NotifySlackObjectArgs = TypedDict(
    "NotifySlackObjectArgs",
    {
        "channels": "List[str]",
        "message": NotRequired["str"],
    },
)


class NotifySlackObject(BaseModel):
    channels: List[str]
    message: Optional[str] = None

    @classmethod
    def from_dict(cls, data: NotifySlackObjectArgs) -> NotifySlackObject:
        return cls.model_validate({**data})


NotifySlackArgs = TypedDict(
    "NotifySlackArgs",
    {
        # A boolean expression that omits the step when false
        "if": NotRequired["If"],
        "slack": NotRequired["str | NotifySlackObjectArgs"],
    },
)


class NotifySlack(BaseModel):
    # A boolean expression that omits the step when false
    step_if: Optional[If] = Field(
        validation_alias=AliasChoices("if", "step_if"),
        serialization_alias="if",
        default=None,
    )
    slack: Optional[str | NotifySlackObject] = None

    @classmethod
    def from_dict(cls, data: NotifySlackArgs) -> NotifySlack:
        step_if = {"step_if": data["if"]} if "if" in data else {}
        return cls.model_validate({**data, **step_if})


NotifyWebhookArgs = TypedDict(
    "NotifyWebhookArgs",
    {
        # A boolean expression that omits the step when false
        "if": NotRequired["If"],
        "webhook": NotRequired["str"],
    },
)


class NotifyWebhook(BaseModel):
    # A boolean expression that omits the step when false
    step_if: Optional[If] = Field(
        validation_alias=AliasChoices("if", "step_if"),
        serialization_alias="if",
        default=None,
    )
    webhook: Optional[str] = None

    @classmethod
    def from_dict(cls, data: NotifyWebhookArgs) -> NotifyWebhook:
        step_if = {"step_if": data["if"]} if "if" in data else {}
        return cls.model_validate({**data, **step_if})


NotifyPagerdutyArgs = TypedDict(
    "NotifyPagerdutyArgs",
    {
        # A boolean expression that omits the step when false
        "if": NotRequired["If"],
        "pagerduty_change_event": NotRequired["str"],
    },
)


class NotifyPagerduty(BaseModel):
    # A boolean expression that omits the step when false
    step_if: Optional[If] = Field(
        validation_alias=AliasChoices("if", "step_if"),
        serialization_alias="if",
        default=None,
    )
    pagerduty_change_event: Optional[str] = None

    @classmethod
    def from_dict(cls, data: NotifyPagerdutyArgs) -> NotifyPagerduty:
        step_if = {"step_if": data["if"]} if "if" in data else {}
        return cls.model_validate({**data, **step_if})


class NotifyGithubCommitStatusGithubCommitStatus(BaseModel):
    # GitHub commit status name
    context: Optional[str] = None

    @classmethod
    def from_dict(
        cls, data: NotifyGithubCommitStatusGithubCommitStatusArgs
    ) -> NotifyGithubCommitStatusGithubCommitStatus:
        return cls.model_validate({**data})


NotifyGithubCommitStatusGithubCommitStatusArgs = TypedDict(
    "NotifyGithubCommitStatusGithubCommitStatusArgs",
    {
        # GitHub commit status name
        "context": NotRequired["str"],
    },
)
NotifyGithubCommitStatusArgs = TypedDict(
    "NotifyGithubCommitStatusArgs",
    {
        "github_commit_status": NotRequired[
            "NotifyGithubCommitStatusGithubCommitStatusArgs"
        ],
        # A boolean expression that omits the step when false
        "if": NotRequired["If"],
    },
)


class NotifyGithubCommitStatus(BaseModel):
    github_commit_status: Optional[NotifyGithubCommitStatusGithubCommitStatus] = None
    # A boolean expression that omits the step when false
    step_if: Optional[If] = Field(
        validation_alias=AliasChoices("if", "step_if"),
        serialization_alias="if",
        default=None,
    )

    @classmethod
    def from_dict(cls, data: NotifyGithubCommitStatusArgs) -> NotifyGithubCommitStatus:
        step_if = {"step_if": data["if"]} if "if" in data else {}
        return cls.model_validate({**data, **step_if})


class NotifyGithubCheckGithubCheckOutputAnnotations(BaseModel):
    # The level of the annotation
    annotation_level: Literal["notice", "warning", "failure"]
    # The end column of the annotation. Only valid when start_line and end_line are equal
    end_column: Optional[int] = None
    # The end line of the annotation
    end_line: int
    # The message for the annotation
    message: str
    # The path of the file to add an annotation to, relative to the repository root
    path: str
    # Additional details for the annotation, displayed alongside the message
    raw_details: Optional[str] = None
    # The start column of the annotation. Only valid when start_line and end_line are equal
    start_column: Optional[int] = None
    # The start line of the annotation
    start_line: int
    # The title for the annotation
    title: Optional[str] = None

    @classmethod
    def from_dict(
        cls, data: NotifyGithubCheckGithubCheckOutputAnnotationsArgs
    ) -> NotifyGithubCheckGithubCheckOutputAnnotations:
        return cls.model_validate({**data})


NotifyGithubCheckGithubCheckOutputAnnotationsArgs = TypedDict(
    "NotifyGithubCheckGithubCheckOutputAnnotationsArgs",
    {
        # The level of the annotation
        "annotation_level": Literal["notice", "warning", "failure"],
        # The end column of the annotation. Only valid when start_line and end_line are equal
        "end_column": NotRequired["int"],
        # The end line of the annotation
        "end_line": "int",
        # The message for the annotation
        "message": "str",
        # The path of the file to add an annotation to, relative to the repository root
        "path": "str",
        # Additional details for the annotation, displayed alongside the message
        "raw_details": NotRequired["str"],
        # The start column of the annotation. Only valid when start_line and end_line are equal
        "start_column": NotRequired["int"],
        # The start line of the annotation
        "start_line": "int",
        # The title for the annotation
        "title": NotRequired["str"],
    },
)


class NotifyGithubCheckGithubCheckOutput(BaseModel):
    annotations: Optional[List[NotifyGithubCheckGithubCheckOutputAnnotations]] = None
    # The summary of the GitHub check's output
    summary: Optional[str] = None
    # The details of the GitHub check's output. Supports Markdown
    text: Optional[str] = None
    # The title of the GitHub check's output
    title: Optional[str] = None

    @classmethod
    def from_dict(
        cls, data: NotifyGithubCheckGithubCheckOutputArgs
    ) -> NotifyGithubCheckGithubCheckOutput:
        return cls.model_validate({**data})


NotifyGithubCheckGithubCheckOutputArgs = TypedDict(
    "NotifyGithubCheckGithubCheckOutputArgs",
    {
        "annotations": NotRequired[
            "List[NotifyGithubCheckGithubCheckOutputAnnotationsArgs]"
        ],
        # The summary of the GitHub check's output
        "summary": NotRequired["str"],
        # The details of the GitHub check's output. Supports Markdown
        "text": NotRequired["str"],
        # The title of the GitHub check's output
        "title": NotRequired["str"],
    },
)


class NotifyGithubCheckGithubCheck(BaseModel):
    # The name of the GitHub check
    name: Optional[str] = None
    output: Optional[NotifyGithubCheckGithubCheckOutput] = None

    @classmethod
    def from_dict(
        cls, data: NotifyGithubCheckGithubCheckArgs
    ) -> NotifyGithubCheckGithubCheck:
        return cls.model_validate({**data})


NotifyGithubCheckGithubCheckArgs = TypedDict(
    "NotifyGithubCheckGithubCheckArgs",
    {
        # The name of the GitHub check
        "name": NotRequired["str"],
        "output": NotRequired["NotifyGithubCheckGithubCheckOutputArgs"],
    },
)

NotifyGithubCheckArgs = TypedDict(
    "NotifyGithubCheckArgs",
    {
        "github_check": NotRequired["NotifyGithubCheckGithubCheckArgs"],
        # A boolean expression that omits the step when false
        "if": NotRequired["If"],
    },
)


class NotifyGithubCheck(BaseModel):
    github_check: Optional[NotifyGithubCheckGithubCheck] = None
    # A boolean expression that omits the step when false
    step_if: Optional[If] = Field(
        validation_alias=AliasChoices("if", "step_if"),
        serialization_alias="if",
        default=None,
    )

    @classmethod
    def from_dict(cls, data: NotifyGithubCheckArgs) -> NotifyGithubCheck:
        step_if = {"step_if": data["if"]} if "if" in data else {}
        return cls.model_validate({**data, **step_if})


# Array of notification options for this step
BuildNotify = List[
    NotifySimple
    | NotifyEmailArgs
    | NotifyEmail
    | NotifyBasecampArgs
    | NotifyBasecamp
    | NotifySlackArgs
    | NotifySlack
    | NotifyWebhookArgs
    | NotifyWebhook
    | NotifyPagerdutyArgs
    | NotifyPagerduty
    | NotifyGithubCommitStatusArgs
    | NotifyGithubCommitStatus
    | NotifyGithubCheckArgs
    | NotifyGithubCheck
]

CacheObjectArgs = TypedDict(
    "CacheObjectArgs",
    {
        "name": NotRequired["str"],
        "paths": NotRequired["List[str]"],
        "size": NotRequired["str"],
    },
)


class CacheObject(BaseModel):
    name: Optional[str] = None
    paths: Optional[List[str]] = None
    size: Optional[str] = None

    @classmethod
    def from_dict(cls, data: CacheObjectArgs) -> CacheObject:
        return cls.model_validate({**data})


# The paths for the caches to be used in the step
Cache = str | List[str] | CacheObject | CacheObjectArgs

# Whether to cancel the job as soon as the build is marked as failing
CancelOnBuildFailing = Literal[True, False, "true", "false"]

PluginsListObject = Dict[str, Any]
# Array of plugins for this step
PluginsList = List[str | Dict[str, Any]]

# A map of plugins for this step. Deprecated: please use the array syntax.
PluginsObject = Dict[str, Any]

MatrixElement = str | int | bool

MatrixElementList = List[str | int | bool]

# Build Matrix dimension element
MatrixAdjustmentsWithObject = Dict[str, str]

SoftFailObjectArgs = TypedDict(
    "SoftFailObjectArgs",
    {
        # The exit status number that will cause this job to soft-fail
        "exit_status": NotRequired[Literal["*"] | int],
    },
)


class SoftFailObject(BaseModel):
    # The exit status number that will cause this job to soft-fail
    exit_status: Optional[Literal["*"] | int] = None

    @classmethod
    def from_dict(cls, data: SoftFailObjectArgs) -> SoftFailObject:
        return cls.model_validate({**data})


SoftFailList = List[SoftFailObject | SoftFailObjectArgs]

# An adjustment to a Build Matrix
MatrixAdjustmentsArgs = TypedDict(
    "MatrixAdjustmentsArgs",
    {
        # Whether this step should be skipped. Passing a string provides a reason for skipping this command
        "skip": NotRequired["Skip"],
        # The conditions for marking the step as a soft-fail.
        "soft_fail": NotRequired["SoftFail"],
        "with": "MatrixElementList | MatrixAdjustmentsWithObject",
    },
)


# An adjustment to a Build Matrix
class MatrixAdjustments(BaseModel):
    # Whether this step should be skipped. Passing a string provides a reason for skipping this command
    skip: Optional[Skip] = None
    # The conditions for marking the step as a soft-fail.
    soft_fail: Optional[SoftFail] = None
    matrix_with: MatrixElementList | MatrixAdjustmentsWithObject = Field(
        validation_alias=AliasChoices("with", "matrix_with"),
        serialization_alias="with",
    )

    @classmethod
    def from_dict(cls, data: MatrixAdjustmentsArgs) -> MatrixAdjustments:
        matrix_with = {"matrix_with": data["with"]} if "with" in data else {}
        return cls.model_validate({**data, **matrix_with})


# Configuration for multi-dimension Build Matrix
MatrixObjectArgs = TypedDict(
    "MatrixObjectArgs",
    {
        # An adjustment to a Build Matrix
        "adjustments": NotRequired["List[MatrixAdjustmentsArgs]"],
        "setup": "MatrixSetup",
    },
)


# Configuration for multi-dimension Build Matrix
class MatrixObject(BaseModel):
    # An adjustment to a Build Matrix
    adjustments: Optional[List[MatrixAdjustments]] = None
    setup: MatrixSetup

    @classmethod
    def from_dict(cls, data: MatrixObjectArgs) -> MatrixObject:
        return cls.model_validate({**data})


CommandStepManualRetryObjectArgs = TypedDict(
    "CommandStepManualRetryObjectArgs",
    {
        # Whether or not this job can be retried manually
        "allowed": NotRequired[Literal[True, False, "true", "false"]],
        # Whether or not this job can be retried after it has passed
        "permit_on_passed": NotRequired[Literal[True, False, "true", "false"]],
        # A string that will be displayed in a tooltip on the Retry button in Buildkite. This will only be displayed if the allowed attribute is set to false.
        "reason": NotRequired["str"],
    },
)


class CommandStepManualRetryObject(BaseModel):
    # Whether or not this job can be retried manually
    allowed: Optional[Literal[True, False, "true", "false"]] = None
    # Whether or not this job can be retried after it has passed
    permit_on_passed: Optional[Literal[True, False, "true", "false"]] = None
    # A string that will be displayed in a tooltip on the Retry button in Buildkite. This will only be displayed if the allowed attribute is set to false.
    reason: Optional[str] = None

    @classmethod
    def from_dict(
        cls, data: CommandStepManualRetryObjectArgs
    ) -> CommandStepManualRetryObject:
        return cls.model_validate({**data})


# The conditions for retrying this step.
class CommandStepRetry(BaseModel):
    # Whether to allow a job to retry automatically. If set to true, the retry conditions are set to the default value.
    automatic: Optional[CommandStepAutomaticRetry] = None
    # Whether to allow a job to be retried manually
    manual: Optional[CommandStepManualRetry] = None

    @classmethod
    def from_dict(cls, data: CommandStepRetryArgs) -> CommandStepRetry:
        return cls.model_validate({**data})


# The conditions for retrying this step.
CommandStepRetryArgs = TypedDict(
    "CommandStepRetryArgs",
    {
        # Whether to allow a job to retry automatically. If set to true, the retry conditions are set to the default value.
        "automatic": NotRequired["CommandStepAutomaticRetry"],
        # Whether to allow a job to be retried manually
        "manual": NotRequired["CommandStepManualRetry"],
    },
)


# The signature of the command step, generally injected by agents at pipeline upload
class CommandStepSignature(BaseModel):
    # The algorithm used to generate the signature
    algorithm: Optional[str] = None
    # The fields that were signed to form the signature value
    signed_fields: Optional[List[str]] = None
    # The signature value, a JWS compact signature with a detached body
    value: Optional[str] = None

    @classmethod
    def from_dict(cls, data: CommandStepSignatureArgs) -> CommandStepSignature:
        return cls.model_validate({**data})


# The signature of the command step, generally injected by agents at pipeline upload
CommandStepSignatureArgs = TypedDict(
    "CommandStepSignatureArgs",
    {
        # The algorithm used to generate the signature
        "algorithm": NotRequired["str"],
        # The fields that were signed to form the signature value
        "signed_fields": NotRequired["List[str]"],
        # The signature value, a JWS compact signature with a detached body
        "value": NotRequired["str"],
    },
)
CommandStepArgs = TypedDict(
    "CommandStepArgs",
    {
        "agents": NotRequired["Agents"],
        # Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
        "allow_dependency_failure": NotRequired["AllowDependencyFailure"],
        # The glob path/s of artifacts to upload once this step has finished running
        "artifact_paths": NotRequired["str | Path | List[str | Path]"],
        # Which branches will include this step in their builds
        "branches": NotRequired["Branches"],
        # The paths for the caches to be used in the step
        "cache": NotRequired["Cache"],
        # Whether to cancel the job as soon as the build is marked as failing
        "cancel_on_build_failing": NotRequired["CancelOnBuildFailing"],
        # The commands to run on the agent
        "command": NotRequired["CommandStepCommand"],
        # The commands to run on the agent
        "commands": NotRequired["CommandStepCommand"],
        # The maximum number of jobs created from this step that are allowed to run at the same time. If you use this attribute, you must also define concurrency_group.
        "concurrency": NotRequired["int"],
        # A unique name for the concurrency group that you are creating with the concurrency attribute
        "concurrency_group": NotRequired["str"],
        # Control command order, allowed values are 'ordered' (default) and 'eager'.  If you use this attribute, you must also define concurrency_group and concurrency.
        "concurrency_method": NotRequired[Literal["ordered", "eager"]],
        # The step keys for a step to depend on
        "depends_on": NotRequired["DependsOn"],
        # Environment variables for this step
        "env": NotRequired["Env"],
        # A unique identifier for a step, must not resemble a UUID
        "id": NotRequired["str"],
        # A unique identifier for a step, must not resemble a UUID
        "identifier": NotRequired["str"],
        # A boolean expression that omits the step when false
        "if": NotRequired["If"],
        # Agent-applied attribute: A glob pattern that omits the step from a build if it does not match any files changed in the build. Can be a single pattern, list of patterns, or an object with include/exclude attributes.
        "if_changed": NotRequired["IfChanged"],
        # (Kubernetes stack only) The container image to use for this pipeline or step
        "image": NotRequired["str"],
        # A unique identifier for a step, must not resemble a UUID
        "key": NotRequired["str"],
        # The label that will be displayed in the pipeline visualisation in Buildkite. Supports emoji.
        "label": NotRequired["str"],
        "matrix": NotRequired["Matrix"],
        # The label that will be displayed in the pipeline visualisation in Buildkite. Supports emoji.
        "name": NotRequired["str"],
        # Array of notification options for this step
        "notify": NotRequired["CommandStepNotify"],
        # The number of parallel jobs that will be created based on this step
        "parallelism": NotRequired["int"],
        "plugins": NotRequired["Plugins"],
        # Priority of all jobs in the pipeline, higher priorities are assigned to agents. When set pipeline-wide, it applies to all steps that do not have their own priority key set.
        "priority": NotRequired["int"],
        # The conditions for retrying this step.
        "retry": NotRequired["CommandStepRetryArgs"],
        # A list of secret names or a mapping of environment variable names to secret names to be made available to the build or step
        "secrets": NotRequired["Secrets"],
        # The signature of the command step, generally injected by agents at pipeline upload
        "signature": NotRequired["CommandStepSignatureArgs"],
        # Whether this step should be skipped. Passing a string provides a reason for skipping this command
        "skip": NotRequired["Skip"],
        # The conditions for marking the step as a soft-fail.
        "soft_fail": NotRequired["SoftFail"],
        # The number of minutes to time out a job
        "timeout_in_minutes": NotRequired["int"],
        "type": NotRequired[Literal["script", "command", "commands"]],
    },
)


class CommandStep(BaseModel):
    agents: Optional[Agents] = None
    # Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
    allow_dependency_failure: Optional[AllowDependencyFailure] = None
    # The glob path/s of artifacts to upload once this step has finished running
    artifact_paths: Optional[str | Path | List[str | Path]] = None
    # Which branches will include this step in their builds
    branches: Optional[Branches] = None
    # The paths for the caches to be used in the step
    cache: Optional[Cache] = None
    # Whether to cancel the job as soon as the build is marked as failing
    cancel_on_build_failing: Optional[CancelOnBuildFailing] = None
    # The commands to run on the agent
    command: Optional[CommandStepCommand] = None
    # The commands to run on the agent
    commands: Optional[CommandStepCommand] = None
    # The maximum number of jobs created from this step that are allowed to run at the same time. If you use this attribute, you must also define concurrency_group.
    concurrency: Optional[int] = None
    # A unique name for the concurrency group that you are creating with the concurrency attribute
    concurrency_group: Optional[str] = None
    # Control command order, allowed values are 'ordered' (default) and 'eager'.  If you use this attribute, you must also define concurrency_group and concurrency.
    concurrency_method: Optional[Literal["ordered", "eager"]] = None
    # The step keys for a step to depend on
    depends_on: Optional[DependsOn] = None
    # Environment variables for this step
    env: Optional[Env] = None
    # A unique identifier for a step, must not resemble a UUID
    id: Optional[str] = None
    # A unique identifier for a step, must not resemble a UUID
    identifier: Optional[str] = None
    # A boolean expression that omits the step when false
    step_if: Optional[If] = Field(
        validation_alias=AliasChoices("if", "step_if"),
        serialization_alias="if",
        default=None,
    )
    # Agent-applied attribute: A glob pattern that omits the step from a build if it does not match any files changed in the build. Can be a single pattern, list of patterns, or an object with include/exclude attributes.
    if_changed: Optional[IfChanged] = None
    # (Kubernetes stack only) The container image to use for this pipeline or step
    image: Optional[str] = None
    # A unique identifier for a step, must not resemble a UUID
    key: Optional[str] = None
    # The label that will be displayed in the pipeline visualisation in Buildkite. Supports emoji.
    label: Optional[str] = None
    matrix: Optional[Matrix] = None
    # The label that will be displayed in the pipeline visualisation in Buildkite. Supports emoji.
    name: Optional[str] = None
    # Array of notification options for this step
    notify: Optional[CommandStepNotify] = None
    # The number of parallel jobs that will be created based on this step
    parallelism: Optional[int] = None
    plugins: Optional[Plugins] = None
    # Priority of all jobs in the pipeline, higher priorities are assigned to agents. When set pipeline-wide, it applies to all steps that do not have their own priority key set.
    priority: Optional[int] = None
    # The conditions for retrying this step.
    retry: Optional[CommandStepRetry] = None
    # A list of secret names or a mapping of environment variable names to secret names to be made available to the build or step
    secrets: Optional[Secrets] = None
    # The signature of the command step, generally injected by agents at pipeline upload
    signature: Optional[CommandStepSignature] = None
    # Whether this step should be skipped. Passing a string provides a reason for skipping this command
    skip: Optional[Skip] = None
    # The conditions for marking the step as a soft-fail.
    soft_fail: Optional[SoftFail] = None
    # The number of minutes to time out a job
    timeout_in_minutes: Optional[int] = None
    type: Optional[Literal["script", "command", "commands"]] = None

    @classmethod
    def from_dict(cls, data: CommandStepArgs) -> CommandStep:
        step_if = {"step_if": data["if"]} if "if" in data else {}
        return cls.model_validate({**data, **step_if})


# Whether to allow a job to retry automatically. If set to true, the retry conditions are set to the default value.
CommandStepAutomaticRetry = (
    Literal[True, False, "true", "false"]
    | AutomaticRetryArgs
    | AutomaticRetry
    | AutomaticRetryList
)

# The commands to run on the agent
CommandStepCommand = List[str] | str

# Whether to allow a job to be retried manually
CommandStepManualRetry = (
    Literal[True, False, "true", "false"]
    | CommandStepManualRetryObjectArgs
    | CommandStepManualRetryObject
)

# Array of notification options for this step
CommandStepNotify = List[
    NotifySimple
    | NotifyBasecampArgs
    | NotifyBasecamp
    | NotifySlackArgs
    | NotifySlack
    | NotifyGithubCommitStatusArgs
    | NotifyGithubCommitStatus
    | NotifyGithubCheckArgs
    | NotifyGithubCheck
]

# The step keys for a step to depend on
DependsOn = str | DependsOnList

# Environment variables for this step
Env = Dict[str, Any]

# A list of input fields required to be filled out before unblocking the step
Fields = List[TextFieldArgs | TextField | SelectFieldArgs | SelectField]

NestedBlockStepArgs = TypedDict(
    "NestedBlockStepArgs",
    {
        "block": NotRequired["BlockStepArgs"],
    },
)


class NestedBlockStep(BaseModel):
    block: Optional[BlockStep] = None

    @classmethod
    def from_dict(cls, data: NestedBlockStepArgs) -> NestedBlockStep:
        return cls.model_validate({**data})


# Pauses the execution of a build and waits on a user to unblock it
StringBlockStep = Literal["block"]

InputStepArgs = TypedDict(
    "InputStepArgs",
    {
        # Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
        "allow_dependency_failure": NotRequired["AllowDependencyFailure"],
        # A list of teams that are permitted to unblock this step, whose values are a list of one or more team slugs or IDs
        "allowed_teams": NotRequired["AllowedTeams"],
        # The state that the build is set to when the build is blocked by this input step
        "blocked_state": NotRequired[Literal["passed", "failed", "running"]],
        # Which branches will include this step in their builds
        "branches": NotRequired["Branches"],
        # The step keys for a step to depend on
        "depends_on": NotRequired["DependsOn"],
        # A list of input fields required to be filled out before unblocking the step
        "fields": NotRequired["Fields"],
        # A unique identifier for a step, must not resemble a UUID
        "id": NotRequired["str"],
        # A unique identifier for a step, must not resemble a UUID
        "identifier": NotRequired["str"],
        # A boolean expression that omits the step when false
        "if": NotRequired["If"],
        # The label of the input step
        "input": NotRequired["str"],
        # A unique identifier for a step, must not resemble a UUID
        "key": NotRequired["str"],
        # The label of the input step
        "label": NotRequired["str"],
        # The label of the input step
        "name": NotRequired["str"],
        # The instructional message displayed in the dialog box when the unblock step is activated
        "prompt": NotRequired["str"],
        "type": NotRequired[Literal["input"]],
    },
)


class InputStep(BaseModel):
    # Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
    allow_dependency_failure: Optional[AllowDependencyFailure] = None
    # A list of teams that are permitted to unblock this step, whose values are a list of one or more team slugs or IDs
    allowed_teams: Optional[AllowedTeams] = None
    # The state that the build is set to when the build is blocked by this input step
    blocked_state: Optional[Literal["passed", "failed", "running"]] = None
    # Which branches will include this step in their builds
    branches: Optional[Branches] = None
    # The step keys for a step to depend on
    depends_on: Optional[DependsOn] = None
    # A list of input fields required to be filled out before unblocking the step
    fields: Optional[Fields] = None
    # A unique identifier for a step, must not resemble a UUID
    id: Optional[str] = None
    # A unique identifier for a step, must not resemble a UUID
    identifier: Optional[str] = None
    # A boolean expression that omits the step when false
    step_if: Optional[If] = Field(
        validation_alias=AliasChoices("if", "step_if"),
        serialization_alias="if",
        default=None,
    )
    # The label of the input step
    input: Optional[str] = None
    # A unique identifier for a step, must not resemble a UUID
    key: Optional[str] = None
    # The label of the input step
    label: Optional[str] = None
    # The label of the input step
    name: Optional[str] = None
    # The instructional message displayed in the dialog box when the unblock step is activated
    prompt: Optional[str] = None
    type: Optional[Literal["input"]] = None

    @classmethod
    def from_dict(cls, data: InputStepArgs) -> InputStep:
        step_if = {"step_if": data["if"]} if "if" in data else {}
        return cls.model_validate({**data, **step_if})


NestedInputStepArgs = TypedDict(
    "NestedInputStepArgs",
    {
        "input": NotRequired["InputStepArgs"],
    },
)


class NestedInputStep(BaseModel):
    input: Optional[InputStep] = None

    @classmethod
    def from_dict(cls, data: NestedInputStepArgs) -> NestedInputStep:
        return cls.model_validate({**data})


# Pauses the execution of a build and waits on a user to unblock it
StringInputStep = Literal["input"]

NestedCommandStepArgs = TypedDict(
    "NestedCommandStepArgs",
    {
        "command": NotRequired["CommandStepArgs"],
        "commands": NotRequired["CommandStepArgs"],
        "script": NotRequired["CommandStepArgs"],
    },
)


class NestedCommandStep(BaseModel):
    command: Optional[CommandStep] = None
    commands: Optional[CommandStep] = None
    script: Optional[CommandStep] = None

    @classmethod
    def from_dict(cls, data: NestedCommandStepArgs) -> NestedCommandStep:
        return cls.model_validate({**data})


WaitStepArgs = TypedDict(
    "WaitStepArgs",
    {
        # Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
        "allow_dependency_failure": NotRequired["AllowDependencyFailure"],
        # Which branches will include this step in their builds
        "branches": NotRequired["Branches"],
        # Continue to the next steps, even if the previous group of steps fail
        "continue_on_failure": NotRequired[Literal[True, False, "true", "false"]],
        # The step keys for a step to depend on
        "depends_on": NotRequired["DependsOn"],
        # A unique identifier for a step, must not resemble a UUID
        "id": NotRequired["str"],
        # A unique identifier for a step, must not resemble a UUID
        "identifier": NotRequired["str"],
        # A boolean expression that omits the step when false
        "if": NotRequired["If"],
        # A unique identifier for a step, must not resemble a UUID
        "key": NotRequired["str"],
        # Waits for previous steps to pass before continuing
        "label": NotRequired["str"],
        # Waits for previous steps to pass before continuing
        "name": NotRequired["str"],
        "type": NotRequired[Literal["wait", "waiter"]],
        # Waits for previous steps to pass before continuing
        "wait": NotRequired["str"],
    },
)


class WaitStep(BaseModel):
    # Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
    allow_dependency_failure: Optional[AllowDependencyFailure] = None
    # Which branches will include this step in their builds
    branches: Optional[Branches] = None
    # Continue to the next steps, even if the previous group of steps fail
    continue_on_failure: Optional[Literal[True, False, "true", "false"]] = None
    # The step keys for a step to depend on
    depends_on: Optional[DependsOn] = None
    # A unique identifier for a step, must not resemble a UUID
    id: Optional[str] = None
    # A unique identifier for a step, must not resemble a UUID
    identifier: Optional[str] = None
    # A boolean expression that omits the step when false
    step_if: Optional[If] = Field(
        validation_alias=AliasChoices("if", "step_if"),
        serialization_alias="if",
        default=None,
    )
    # A unique identifier for a step, must not resemble a UUID
    key: Optional[str] = None
    # Waits for previous steps to pass before continuing
    label: Optional[str] = None
    # Waits for previous steps to pass before continuing
    name: Optional[str] = None
    type: Optional[Literal["wait", "waiter"]] = None
    # Waits for previous steps to pass before continuing
    wait: Optional[str] = None

    @classmethod
    def from_dict(cls, data: WaitStepArgs) -> WaitStep:
        step_if = {"step_if": data["if"]} if "if" in data else {}
        return cls.model_validate({**data, **step_if})


NestedWaitStepArgs = TypedDict(
    "NestedWaitStepArgs",
    {
        "wait": NotRequired["WaitStepArgs"],
        "waiter": NotRequired["WaitStepArgs"],
    },
)


class NestedWaitStep(BaseModel):
    wait: Optional[WaitStep] = None
    waiter: Optional[WaitStep] = None

    @classmethod
    def from_dict(cls, data: NestedWaitStepArgs) -> NestedWaitStep:
        return cls.model_validate({**data})


# Waits for previous steps to pass before continuing
StringWaitStep = Literal["wait", "waiter"]


# Properties of the build that will be created when the step is triggered
class TriggerStepBuild(BaseModel):
    # The branch for the build
    branch: Optional[str] = None
    # The commit hash for the build
    commit: Optional[str] = None
    # Environment variables for this step
    env: Optional[Env] = None
    # The message for the build (supports emoji)
    message: Optional[str] = None
    # Meta-data for the build
    meta_data: Optional[Dict[str, Any]] = None

    @classmethod
    def from_dict(cls, data: TriggerStepBuildArgs) -> TriggerStepBuild:
        return cls.model_validate({**data})


# Properties of the build that will be created when the step is triggered
TriggerStepBuildArgs = TypedDict(
    "TriggerStepBuildArgs",
    {
        # The branch for the build
        "branch": NotRequired["str"],
        # The commit hash for the build
        "commit": NotRequired["str"],
        # Environment variables for this step
        "env": NotRequired["Env"],
        # The message for the build (supports emoji)
        "message": NotRequired["str"],
        # Meta-data for the build
        "meta_data": NotRequired["Dict[str, Any]"],
    },
)
TriggerStepArgs = TypedDict(
    "TriggerStepArgs",
    {
        # Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
        "allow_dependency_failure": NotRequired["AllowDependencyFailure"],
        # Whether to continue the build without waiting for the triggered step to complete
        "async": NotRequired[Literal[True, False, "true", "false"]],
        # Which branches will include this step in their builds
        "branches": NotRequired["Branches"],
        # Properties of the build that will be created when the step is triggered
        "build": NotRequired["TriggerStepBuildArgs"],
        # The step keys for a step to depend on
        "depends_on": NotRequired["DependsOn"],
        # A unique identifier for a step, must not resemble a UUID
        "id": NotRequired["str"],
        # A unique identifier for a step, must not resemble a UUID
        "identifier": NotRequired["str"],
        # A boolean expression that omits the step when false
        "if": NotRequired["If"],
        # Agent-applied attribute: A glob pattern that omits the step from a build if it does not match any files changed in the build. Can be a single pattern, list of patterns, or an object with include/exclude attributes.
        "if_changed": NotRequired["IfChanged"],
        # A unique identifier for a step, must not resemble a UUID
        "key": NotRequired["str"],
        # The label that will be displayed in the pipeline visualisation in Buildkite. Supports emoji.
        "label": NotRequired["str"],
        # The label that will be displayed in the pipeline visualisation in Buildkite. Supports emoji.
        "name": NotRequired["str"],
        # Whether this step should be skipped. Passing a string provides a reason for skipping this command
        "skip": NotRequired["Skip"],
        # The conditions for marking the step as a soft-fail.
        "soft_fail": NotRequired["SoftFail"],
        # The slug of the pipeline to create a build
        "trigger": "str",
        "type": NotRequired[Literal["trigger"]],
    },
)


class TriggerStep(BaseModel):
    # Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
    allow_dependency_failure: Optional[AllowDependencyFailure] = None
    # Whether to continue the build without waiting for the triggered step to complete
    step_async: Optional[Literal[True, False, "true", "false"]] = Field(
        validation_alias=AliasChoices("async", "step_async"),
        serialization_alias="async",
        default=None,
    )
    # Which branches will include this step in their builds
    branches: Optional[Branches] = None
    # Properties of the build that will be created when the step is triggered
    build: Optional[TriggerStepBuild] = None
    # The step keys for a step to depend on
    depends_on: Optional[DependsOn] = None
    # A unique identifier for a step, must not resemble a UUID
    id: Optional[str] = None
    # A unique identifier for a step, must not resemble a UUID
    identifier: Optional[str] = None
    # A boolean expression that omits the step when false
    step_if: Optional[If] = Field(
        validation_alias=AliasChoices("if", "step_if"),
        serialization_alias="if",
        default=None,
    )
    # Agent-applied attribute: A glob pattern that omits the step from a build if it does not match any files changed in the build. Can be a single pattern, list of patterns, or an object with include/exclude attributes.
    if_changed: Optional[IfChanged] = None
    # A unique identifier for a step, must not resemble a UUID
    key: Optional[str] = None
    # The label that will be displayed in the pipeline visualisation in Buildkite. Supports emoji.
    label: Optional[str] = None
    # The label that will be displayed in the pipeline visualisation in Buildkite. Supports emoji.
    name: Optional[str] = None
    # Whether this step should be skipped. Passing a string provides a reason for skipping this command
    skip: Optional[Skip] = None
    # The conditions for marking the step as a soft-fail.
    soft_fail: Optional[SoftFail] = None
    # The slug of the pipeline to create a build
    trigger: str
    type: Optional[Literal["trigger"]] = None

    @classmethod
    def from_dict(cls, data: TriggerStepArgs) -> TriggerStep:
        step_if = {"step_if": data["if"]} if "if" in data else {}
        step_async = {"step_async": data["async"]} if "async" in data else {}
        return cls.model_validate({**data, **step_if, **step_async})


NestedTriggerStepArgs = TypedDict(
    "NestedTriggerStepArgs",
    {
        "trigger": NotRequired["TriggerStepArgs"],
    },
)


class NestedTriggerStep(BaseModel):
    trigger: Optional[TriggerStep] = None

    @classmethod
    def from_dict(cls, data: NestedTriggerStepArgs) -> NestedTriggerStep:
        return cls.model_validate({**data})


GroupStepArgs = TypedDict(
    "GroupStepArgs",
    {
        # Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
        "allow_dependency_failure": NotRequired["AllowDependencyFailure"],
        # The step keys for a step to depend on
        "depends_on": NotRequired["DependsOn"],
        # The name to give to this group of steps
        "group": "str",
        # A unique identifier for a step, must not resemble a UUID
        "id": NotRequired["str"],
        # A unique identifier for a step, must not resemble a UUID
        "identifier": NotRequired["str"],
        # A boolean expression that omits the step when false
        "if": NotRequired["If"],
        # Agent-applied attribute: A glob pattern that omits the step from a build if it does not match any files changed in the build. Can be a single pattern, list of patterns, or an object with include/exclude attributes.
        "if_changed": NotRequired["IfChanged"],
        # A unique identifier for a step, must not resemble a UUID
        "key": NotRequired["str"],
        # The name to give to this group of steps
        "label": NotRequired["str"],
        # The name to give to this group of steps
        "name": NotRequired["str"],
        # Array of notification options for this step
        "notify": NotRequired["BuildNotify"],
        # Whether this step should be skipped. Passing a string provides a reason for skipping this command
        "skip": NotRequired["Skip"],
        # A list of steps
        "steps": "GroupSteps",
    },
)


class GroupStep(BaseModel):
    # Whether to proceed with this step and further steps if a step named in the depends_on attribute fails
    allow_dependency_failure: Optional[AllowDependencyFailure] = None
    # The step keys for a step to depend on
    depends_on: Optional[DependsOn] = None
    # The name to give to this group of steps
    group: str
    # A unique identifier for a step, must not resemble a UUID
    id: Optional[str] = None
    # A unique identifier for a step, must not resemble a UUID
    identifier: Optional[str] = None
    # A boolean expression that omits the step when false
    step_if: Optional[If] = Field(
        validation_alias=AliasChoices("if", "step_if"),
        serialization_alias="if",
        default=None,
    )
    # Agent-applied attribute: A glob pattern that omits the step from a build if it does not match any files changed in the build. Can be a single pattern, list of patterns, or an object with include/exclude attributes.
    if_changed: Optional[IfChanged] = None
    # A unique identifier for a step, must not resemble a UUID
    key: Optional[str] = None
    # The name to give to this group of steps
    label: Optional[str] = None
    # The name to give to this group of steps
    name: Optional[str] = None
    # Array of notification options for this step
    notify: Optional[BuildNotify] = None
    # Whether this step should be skipped. Passing a string provides a reason for skipping this command
    skip: Optional[Skip] = None
    # A list of steps
    steps: GroupSteps

    @classmethod
    def from_dict(cls, data: GroupStepArgs) -> GroupStep:
        step_if = {"step_if": data["if"]} if "if" in data else {}
        return cls.model_validate({**data, **step_if})


# A list of steps
GroupSteps = List[
    BlockStepArgs
    | BlockStep
    | NestedBlockStepArgs
    | NestedBlockStep
    | StringBlockStep
    | InputStepArgs
    | InputStep
    | NestedInputStepArgs
    | NestedInputStep
    | StringInputStep
    | CommandStepArgs
    | CommandStep
    | NestedCommandStepArgs
    | NestedCommandStep
    | WaitStepArgs
    | WaitStep
    | NestedWaitStepArgs
    | NestedWaitStep
    | StringWaitStep
    | TriggerStepArgs
    | TriggerStep
    | NestedTriggerStepArgs
    | NestedTriggerStep
]

# A boolean expression that omits the step when false
If = str

IfChangedObjectArgs = TypedDict(
    "IfChangedObjectArgs",
    {
        # Pattern or list of patterns to exclude
        "exclude": NotRequired["str | List[str]"],
        # Pattern or list of patterns to include
        "include": NotRequired["str | List[str]"],
    },
)


class IfChangedObject(BaseModel):
    # Pattern or list of patterns to exclude
    exclude: Optional[str | List[str]] = None
    # Pattern or list of patterns to include
    include: Optional[str | List[str]] = None

    @classmethod
    def from_dict(cls, data: IfChangedObjectArgs) -> IfChangedObject:
        return cls.model_validate({**data})


# Agent-applied attribute: A glob pattern that omits the step from a build if it does not match any files changed in the build. Can be a single pattern, list of patterns, or an object with include/exclude attributes.
IfChanged = str | List[str] | IfChangedObject | IfChangedObjectArgs

# (Kubernetes stack only) The container image to use for this pipeline or step
Image = str

# A unique identifier for a step, must not resemble a UUID
Key = str

# The label that will be displayed in the pipeline visualisation in Buildkite. Supports emoji.
Label = str

Matrix = MatrixElementList | MatrixObjectArgs | MatrixObject

MatrixSetupObject = Dict[str, List[str | int | bool]]
MatrixSetup = MatrixElementList | Dict[str, List[str | int | bool]]

# A list of steps
PipelineSteps = List[
    BlockStepArgs
    | BlockStep
    | NestedBlockStepArgs
    | NestedBlockStep
    | StringBlockStep
    | InputStepArgs
    | InputStep
    | NestedInputStepArgs
    | NestedInputStep
    | StringInputStep
    | CommandStepArgs
    | CommandStep
    | NestedCommandStepArgs
    | NestedCommandStep
    | WaitStepArgs
    | WaitStep
    | NestedWaitStepArgs
    | NestedWaitStep
    | StringWaitStep
    | TriggerStepArgs
    | TriggerStep
    | NestedTriggerStepArgs
    | NestedTriggerStep
    | GroupStepArgs
    | GroupStep
]

Plugins = PluginsList | PluginsObject

# Priority of all jobs in the pipeline, higher priorities are assigned to agents. When set pipeline-wide, it applies to all steps that do not have their own priority key set.
Priority = int

# The instructional message displayed in the dialog box when the unblock step is activated
Prompt = str

SecretsObject = Dict[str, str]
# A list of secret names or a mapping of environment variable names to secret names to be made available to the build or step
Secrets = List[str] | Dict[str, str]

# Whether this step should be skipped. Passing a string provides a reason for skipping this command
Skip = bool | str

# The conditions for marking the step as a soft-fail.
SoftFail = Literal[True, False, "true", "false"] | SoftFailList
